typeset -U path
# path=(path1 path2 ...) -- パスの設定
path=(~/bin $path[@])

export XDG_CONFIG_HOME=${HOME}/.config

export GOPATH=~/Code/go
export PATH="$PATH:$GOPATH/bin"

# ツールの設定
export EDITOR=nvim
export MANWIDTH=100
